Dragoon-Project-Squad/bomberbird

project.godot
scenes/lobby.tscn
scenes/main_menu.tscn
scripts/gamestate.gd

- Made lobby actually appear
- Corrected lobby colors
- Made sure chonkgoon actually is the default in the code, not just on screen

Bugfixpatch0.2.0.1

---

project.godot
scenes/lobby.tscn
scenes/player.tscn
scripts/aiplayer.gd
scripts/gamestate.gd
scripts/lobby.gd
scripts/player_spawner.gd

Disabled skin swapping to prevent multiplayer issues

---

scripts/aiplayer.gd
scripts/player.gd

- movement animation now do not overwrite/stop the death animation from playing
- put player movement animation into its own function for parity with ai player

Fix to issue 81

---

scripts/gamestate.gd
scripts/main_menu.gd

Added basic singleplayer startup functionality

---

scripts/gamestate.gd

Fixes #92
This implements the following functionality:
- When a player disconnects they are removed from the game on clients.
- If all players disconnect the game ends.
- If the server disconnects the game ends.
If you have any changes or would like different functionality just leave a comment.

Graceful disconnect

---

scenes/main_menu.tscn
scripts/gamestate.gd
scripts/lobby.gd

Game hangs on join if server is unreachable

---

scripts/gamestate.gd

Fixed race condition in startup checking

---

scenes/battlegrounds.tscn
scenes/unbreakable.tscn
scenes/unbreakable_spawner.gd

Unbreakable Spawner

---

scripts/main_menu.gd

blocked menu interactions during gameplay

---

scenes/battlegrounds.tscn
scenes/misobon_aiplayer.tscn
scenes/misobon_player.tscn
scenes/unbreakable.tscn
scripts/bomb.gd
scripts/player.gd

Figured out calling functions, bombs return to player when they explode, and stock tracking is implemented for bombs. From how the code works looks like it should automatically increment total and current count of bombs when a player grabs the pickup to increase bomb count.

Stock placement is implemented

---

scripts/ai_state/ai_state_machine.gd
scripts/ai_state/ai_wander.gd
scripts/ai_state/state.gd
scripts/aiplayer.gd
scripts/gamestate.gd
scripts/world.gd

State machine foundation for AI behaviour, one State already created (Wandering)
TO DO:
- Clean aiplayer.gd
- Create more states

24 smart ai opponents new

---

scenes/ai_player.tscn
scripts/ai_player.gd
scripts/ai_state/ai_state_machine.gd
scripts/ai_state/ai_wander.gd
scripts/ai_state/state.gd

Fix to AI not moving

---

scripts/explosion.gd
scripts/gamestate.gd
scripts/lobby.gd
scripts/misobon_player.gd
scripts/player.gd

Fixes an additional bug allowing the revival of misobon players on Misobon More on
Also updated some other places that used the misobon mode variable to use the global one

Fixed another issue that let players keep reviving on Misobon Mode on

---

scripts/ai_state/ai_bomb.gd
scripts/ai_state/ai_dodge.gd
scripts/ai_state/ai_state_machine.gd
scripts/ai_state/ai_wander.gd
scripts/ai_state/state.gd
scripts/bomb_pool.gd
scripts/pickups/default_pickup.gd
scripts/player.gd
scripts/stationary_bomb.gd
scripts/world.gd

Fixed AI Dodge state
- No longer crashes the game
- Finds safe place most of the time (requires further testing)

166 fix ai dodge mechanicstate

---

scenes/battlegrounds.tscn
scripts/held_pickups.gd
scripts/pick_up_pool.gd
scripts/pickups/default_pickup.gd
scripts/player.gd
scripts/world_data.gd

closes #156 but depends on #164 hence stays in draft untill #164 is merged

Item spread on death

---

scenes/battlegrounds.tscn
scenes/misobon_ai_player.tscn
scripts/ai_player.gd
scripts/misobon_ai_bombing.gd
scripts/misobon_ai_player.gd
scripts/misobon_ai_state.gd
scripts/misobon_ai_state_machine.gd
scripts/misobon_ai_wander.gd
scripts/misobon_path.gd
scripts/misobon_player.gd
scripts/world_data.gd

WIP of a simple Misobon AI consisting of these 4 items:

Misobon AI

---

project.godot
resources/settings/player_keybind_default.tres
scenes/bombs/bomb_pool.tscn
scenes/options_menu/settings_tab_container.tscn
scripts/stationary_bomb.gd

- Returned Bomb Pool AudioStreamer to 2D
- Updated General tab in options
- Fixed keybind
- updated version num

fixed audio crash and updated keybinds

---

autoloads/gamestate.gd
autoloads/globals.gd
players_manager.gd
scenes/battlegrounds.tscn
scenes/hurry_up.gd
scripts/ai_state/ai_state_machine.gd
scripts/airborn_bomb.gd
scripts/bomb_root_fsm.gd
scripts/breakable.gd
scripts/breakable_spawner.gd
scripts/main_menu.gd
scripts/misobon_player.gd
scripts/pickups/default_pickup.gd
scripts/pickups/explosion_boost.gd
scripts/pickups/extra_bomb.gd
scripts/pickups/max_explosion.gd
scripts/pickups/punch_ability.gd
scripts/pickups/speed_boost.gd
scripts/player.gd
scripts/stationary_bomb.gd
scripts/world.gd

Does pretty much just what #196 describes and also fixes a bug that broke misobon respawn.

Removing tree traversale for world and player nodes (Implements #196)

---

scenes/battlegrounds.tscn
scenes/world.tscn
scripts/music.gd
scripts/world/world.gd
scripts/world/zone.gd

Pretty much just solves #199. Also solves a small bug that caused music files to be loaded twice into the steam (tho unsure if that actually had any effect)

moved music code into its own node

---

autoloads/world_data.gd
scenes/ai_player.tscn
scenes/human_player.tscn
scripts/airborn_bomb.gd
scripts/world/randomized_stage.gd

Removes debug statements introduced by #201

Removing debugging print statements

---

autoloads/gamestate.gd
scripts/cssmenu/character_select_screen.gd
scripts/player_spawner.gd

Fixed a small issue where no valid character was set in the current (and temporary) singleplayer

Fixed SP button crashing

---

autoloads/globals.gd
autoloads/settings_data_container.gd
resources/gameplay/battle_settings.gd
scenes/battlemode_game.tscn
scripts/battlemode_game.gd
scripts/game.gd
scripts/ui/lobby/breakable_spawn_rule_dropdown_button.gd
scripts/ui/lobby/cpu_count_dropdown_button.gd
scripts/ui/lobby/cpu_difficulty_dropdown_button.gd
scripts/ui/lobby/misobon_dropdown_button.gd
scripts/ui/lobby/pickup_spawn_rule_dropdown_button.gd
scripts/world/randomized_stage.gd
scripts/world/world.gd

Fixed global associations to breakable spawns and made stage selection dynamic

---

scenes/level_graph/stage_cell_ui.tscn
scripts/breakable.gd
scripts/level_graph/stage_cell_ui.gd

From the top left to bottom right:
Random, None, Extra Bomb, Explosion Up, Speed Up, Max Explosion, Punch, Not Implemented.

Applied the new icons to the Graph Drawing UI

---

scenes/options_menu/settings_tab_container.gd
scenes/options_menu/settings_tab_container.gd.uid
scenes/options_menu/settings_tab_container.tscn
scripts/ui/options_menu/options.gd

Adjusted the scripts for the options menu to allow for moving between menu tabs using UI keys and the inputs set in the settings menu.

Adding Inputs for Options Menu

---

autoloads/audio_manager.gd
autoloads/audio_manager.gd.uid
project.godot
scenes/debug_campaign_selector.tscn
scenes/ingame_ui/record_winner.tscn
scenes/level_graph/stage_data_ui.tscn
scenes/level_graph/stage_node.tscn
scenes/lobby/battle_settings.tscn
scenes/lobby/lobby.tscn
scenes/main_menu.tscn
scenes/options_menu/hotkey_rebind_button.tscn
scenes/options_menu/options_menu.tscn
scenes/stages/world.tscn
scripts/ui/ingame_ui/se_button.gd
scripts/ui/ingame_ui/se_button.gd.uid
scripts/ui/main_menu.gd

New button subclass SeButton
Replace most ui button uses with it
plays click.wav
closes #79

Button sound effects

---

resources/settings/player_keybind_default.tres
scripts/level_graph/stage_cell_ui.gd

552ddfa broke #263 again this fixes it again

drawing ui pickup fix II

---

resources/gameplay/held_pickups.gd
resources/gameplay/pickup_table.gd
scenes/breakable.tscn
scenes/pickups/piercing_bomb.tscn
scripts/bomb_root_fsm.gd
scripts/breakable.gd
scripts/pick_up_pool.gd
scripts/pickups/piercing_bomb.gd
scripts/pickups/piercing_bomb.gd.uid
scripts/player.gd
scripts/powerup_spawner.gd
scripts/stationary_bomb.gd

#230 
- breaching charge: goes through breakables
- player has a toggle for pierce
- bomb has a dict for additional addons
- changed raycast code for bomb
- small pickup chance

breaching charge

---

resources/gameplay/pickup_table.gd
resources/settings/player_keybind_default.tres
scenes/enemies/ai_player_TEST.tscn
scenes/human_player.tscn
scenes/pick_up_pool.tscn
scenes/pickups/bomb_clip.tscn
scenes/pickups/wall_clip.tscn
scripts/pick_up_pool.gd
scripts/pickups/bomb_clip.gd
scripts/pickups/bomb_clip.gd.uid
scripts/pickups/speed_boost.tscn
scripts/pickups/wall_clip.gd
scripts/pickups/wall_clip.gd.uid
scripts/player.gd
scripts/powerup_spawner.gd

add _clip powerups

---

scenes/explosion.tscn
scripts/bomb_root_fsm.gd
scripts/explosion.gd
scripts/stationary_bomb.gd

#261 
- added exploded function to stationary bombs only
- mask changed to read bombs
- small change to explosion script logic

created bomb chain

---

scenes/bombs/stationary_bomb.tscn

Simple change, collission added to layer 8 in Bomb scene

Layer added for bomb detection

---

resources/gameplay/held_pickups.gd
resources/gameplay/pickup_table.gd
scenes/bombs/stationary_bomb.tscn
scenes/pickups/land_mine.tscn
scripts/bomb_root_fsm.gd
scripts/pick_up_pool.gd
scripts/pickups/land_mine.gd
scripts/pickups/land_mine.gd.uid
scripts/player.gd
scripts/powerup_spawner.gd
scripts/stationary_bomb.gd

Added landmine #229

---

resources/gameplay/held_pickups.gd
resources/gameplay/pickup_table.gd
scenes/human_player.tscn
scenes/pickups/throw_bomb.tscn
scripts/bomb_root_fsm.gd
scripts/human_player.gd
scripts/human_player_controls.gd
scripts/pick_up_pool.gd
scripts/pickups/throw_bomb.gd
scripts/pickups/throw_bomb.gd.uid
scripts/player.gd
scripts/powerup_spawner.gd

#227 
- low chance of dropping (set to 50)
- punch and throw pickups
- #### Throw
- use 'F' key to pickup bomb, press again to throw 3 tiles away
- pauses fuse while carrying
- resumes when thrown
- #### Punch
- use 'E' key to punch a bomb 3 tiles away
- similar to throw ability

throw bombs

---

scripts/ui/lobby/battle_settings.gd

Quick and dirty fix of ui controls triggered while in game

Fixed ui popping up on pressing space while in game

---

scenes/cssmenu/character_select_screen.tscn
scenes/cssmenu/css_player_view.tscn
scenes/lobby/connection_screen.gd
scripts/ui/cssmenu/character_select_screen.gd
scripts/ui/cssmenu/css_player_view.gd

1. Fixed "click to add cpu" showing to client.
2. Fixed it showing for a frame on connection.
3. Fixed link to find ip not working.

Bunch of minor fixes

---

scenes/battlemode_game.tscn

Fixed exit game button not working on end screen

---

autoloads/world_data.gd
resources/gameplay/held_pickups.gd
scenes/enemies/retro_doki_boss.tscn
scenes/enemies/tomato_boss.tscn
scenes/human_player.tscn
scripts/bomb/bomb_root_fsm.gd
scripts/bomb/stationary_bomb.gd
scripts/enemy/ability_detector.gd
scripts/enemy/ability_detector.gd.uid
scripts/enemy/boss.gd
scripts/enemy/detection_handlers/detection_handler_type_retro_doki.gd
scripts/enemy/enemy_state_machine.gd
scripts/enemy/other_states/boss_carry.gd
scripts/enemy/other_states/boss_carry.gd.uid
scripts/enemy/other_states/boss_kick.gd
scripts/enemy/other_states/boss_kick.gd.uid
scripts/enemy/other_states/boss_punch.gd
scripts/enemy/other_states/boss_punch.gd.uid
scripts/enemy/other_states/enemy_chase_path_type.gd
scripts/enemy/other_states/enemy_dodge_path_type.gd
scripts/enemy/wander_types/enemy_wander_path_type.gd
scripts/player/player.gd

Gives the bosses the ability to pickup and use active pickups such as: Punch, Throw and Kick.
Also Retro Doki now spawns with the punch pickup.
For easy testing one can replace the tomato boss in the BOSS ONLY graph with Retro Doki since she does not spawn in the default campaign yet.

handler for active abilities for bosses

---

scripts/ui/cssmenu/character_select_screen.gd
scripts/ui/cssmenu/css_player_view.gd

Added a way to remove cpu from lobby with click

---

autoloads/gamestate.gd
scripts/battlemode_game.gd
scripts/victory_screen.gd

Fixed both races inside victory screen

---

project.godot
resources/settings/player_keybind_default.tres
scenes/bombs/stationary_bomb.tscn
scenes/enemies/alt_doki_boss.tscn
scenes/enemy_components/timezone.tscn
scripts/enemy/abilities/boss_geta_ability.gd
scripts/enemy/abilities/boss_time_ability.gd
scripts/enemy/abilities/boss_time_ability.gd.uid
scripts/enemy/abilities/enemy_tank_ability.gd
scripts/enemy/ability_detector.gd
scripts/enemy/boss.gd
scripts/enemy/detection_handlers/detection_handler_type_alt_doki.gd
scripts/enemy/detection_handlers/detection_handler_type_alt_doki.gd.uid
scripts/enemy/other_states/enemy_chase_path_type.gd
scripts/enemy/other_states/enemy_dodge_path_type.gd
scripts/enemy/timezone.gd
scripts/enemy/timezone.gd.uid
scripts/enemy/wander_types/enemy_wander_path_type.gd
scripts/game.gd
scripts/level_graph/stage_data_ui.gd
scripts/pickups/clock.gd
scripts/pickups/default_pickup.gd

Copy of [Terrorin](https://bomberman.fandom.com/wiki/Terrorin)

added alt-doki-boss

---

resources/settings/player_keybind_default.tres
scenes/exit.tscn
scripts/level_graph/level_graph.gd

Copying stages from on graph into another used to be quite buggy this pr fixes this

Fixes an issue with copying stages in the Level Graph

---

scenes/battlemode_game.tscn

Closes #287 
https://github.com/user-attachments/assets/a700def7-119d-4d8a-ac15-9f3d35e18d45

Added countdown timer visuals

---

resources/gameplay/pickup_table.gd
scenes/pickups/one_up.tscn
scripts/pickups/one_up.gd
scripts/pickups/one_up.gd.uid
scripts/pickups/pick_up_pool.gd
scripts/pickups/powerup_spawner.gd
scripts/player/player.gd

382 one up

---

project.godot

updated version num

---

resources/settings/player_keybind_default.tres
scenes/falling_unbreakable.tscn
scenes/stages/beach_stages/beach_rand.tscn
scenes/stages/desert_stages/desert_rand.tscn
scenes/stages/dungeon_stages/dungeon_rand.tscn
scenes/stages/lab_stages/lab_rand.tscn
scenes/stages/secret_stages/secret_rand.tscn
scripts/falling_unbreakable.gd
scripts/world/hurry_up.gd

fixes hurry up so each stage now has the correct unbreakable spawning and the color of the falling unbreakable fits

hurry up texture fix

---

scripts/ui/cssmenu/character_select_screen.gd

select defaultgoon skin when loading in as host

---

autoloads/gamestate.gd
resources/settings/player_keybind_default.tres
scenes/CREDITS/logo64.png.import
scenes/ai_player.tscn
scenes/battlemode_game.tscn
scripts/ai_state/ai_wander.gd
scripts/battlemode_game.gd
scripts/pickups/pick_up_pool.gd
scripts/player/players_manager.gd
scripts/world/hurry_up.gd

- 3 Player Lobbies no longer break due to bad assertions and RPC
- AI no longer breaks on 2nd round start
- Added shielding to some signal calls
- Fixed edge case with misobon not being created yet on dead players

Fixed several multiplayer bugs

---

autoloads/gamestate.gd

Fixed css not updated on player join

---

autoloads/gamestate.gd
autoloads/settings_data_container.gd
scenes/CREDITS/logo64.png.import
scenes/battlemode_game.tscn
scripts/battlemode_game.gd
scripts/ui/lobby/battle_settings.gd
scripts/ui/lobby/lobby.gd
scripts/ui/lobby/stage_select.gd

Closes #485 
Closes #452 
Fixed undocumented netcode bugs related to closing games and starting new ones
Removed some outdated debugging print statements

Fixed several MP bugs

---

scenes/CREDITS/logo64.png.import
scenes/mus/bountyhunterjam.tscn
scenes/mus/dad_drive.tscn
scenes/mus/random_music.tscn
scenes/mus/rush.tscn
scenes/mus/secret_mus.tscn
scripts/music.gd

fixes https://github.com/Dragoon-Project-Squad/bomberbird/issues/481

Fix to issue 481

---

Wwise/resources/WwiseProjectData.tres
resources/settings/player_keybind_default.tres
scenes/lobby/mode_select.tscn
scenes/lobby/sp_lobby.tscn
scripts/debug_campaign_selector.gd
scripts/ui/lobby/mode_select.gd
scripts/ui/lobby/sp_lobby.gd

added a shorter version of the campaign
